// Arkade Playground — Client-side binding generator
// Mirrors arkade-bindgen's TypeScript and Go backends in JavaScript.
// Takes a compiled JSON artifact string and produces typed SDK code.

// ─── Naming utilities ────────────────────────────────────────────────

function splitWords(s) {
    const words = [];
    let current = '';
    for (const ch of s) {
        if (ch === '_') {
            if (current) { words.push(current); current = ''; }
        } else if (ch >= 'A' && ch <= 'Z' && current.length > 0) {
            const prevUpper = current[current.length - 1] >= 'A' && current[current.length - 1] <= 'Z';
            if (prevUpper) {
                current += ch;
            } else {
                words.push(current); current = ch;
            }
        } else {
            current += ch;
        }
    }
    if (current) words.push(current);
    return words;
}

function toPascalCase(s) {
    if (!s) return '';
    if (/^[A-Z0-9]+$/.test(s)) return s;
    return splitWords(s).map(w => w[0].toUpperCase() + w.slice(1).toLowerCase()).join('');
}

function toCamelCase(s) {
    if (/^[A-Z0-9]+$/.test(s)) return s.toLowerCase();
    const p = toPascalCase(s);
    return p[0].toLowerCase() + p.slice(1);
}

function toSnakeCase(s) {
    if (!s) return '';
    if (/^[A-Z0-9]+$/.test(s)) return s.toLowerCase();
    return splitWords(s).map(w => w.toLowerCase()).join('_');
}

// ─── Encoding inference ──────────────────────────────────────────────

function inferEncoding(typeStr) {
    const map = {
        pubkey: 'compressed-33', signature: 'schnorr-64',
        bytes: 'raw', bytes20: 'raw-20', bytes32: 'raw-32',
        int: 'scriptnum', bool: 'scriptnum', asset: 'raw-32',
    };
    return map[typeStr] || 'raw';
}

// ─── IR construction ─────────────────────────────────────────────────

function buildIR(artifact) {
    const constructorFields = (artifact.constructorInputs || []).map(p => ({
        name: p.name, arkType: p.type, encoding: inferEncoding(p.type),
    }));

    // Group functions by name, pair cooperative + exit
    const groups = new Map();
    for (const func of artifact.functions) {
        if (!groups.has(func.name)) groups.set(func.name, []);
        groups.get(func.name).push(func);
    }

    const functions = [];
    for (const [name, variants] of groups) {
        const coop = variants.find(v => v.serverVariant === true);
        const exit = variants.find(v => v.serverVariant === false);
        if (!coop || !exit) continue;
        functions.push({
            name,
            cooperative: buildVariant(coop),
            exit: buildVariant(exit),
        });
    }

    return {
        name: artifact.contractName,
        constructorFields,
        functions,
        compilerVersion: artifact.compiler?.version || 'unknown',
    };
}

function buildVariant(func) {
    const hasSchema = func.witnessSchema && func.witnessSchema.length > 0;
    const userDeclaredServerSig = (func.functionInputs || []).some(fi => fi.name === 'serverSig');

    let allFields;
    if (hasSchema) {
        allFields = func.witnessSchema.map(w => ({
            name: w.name, arkType: w.type, encoding: w.encoding,
            isServerInjected: func.serverVariant && w.name === 'serverSig' && !userDeclaredServerSig,
        }));
    } else {
        allFields = (func.functionInputs || []).map(fi => ({
            name: fi.name, arkType: fi.type, encoding: inferEncoding(fi.type),
            isServerInjected: false,
        }));
        if (func.serverVariant && !userDeclaredServerSig) {
            allFields.push({ name: 'serverSig', arkType: 'signature', encoding: 'schnorr-64', isServerInjected: true });
        }
    }

    const userFields = allFields.filter(f => !f.isServerInjected);
    const isNofnFallback = (func.require || []).some(r => r.type === 'nOfNMultisig');

    return { userFields, allFields, isNofnFallback };
}

// ─── TypeScript backend ──────────────────────────────────────────────

const TS_TYPE_MAP = {
    'compressed-33': 'Pubkey', 'schnorr-64': 'Signature',
    'raw': 'Bytes', 'raw-20': 'Bytes20', 'raw-32': 'Bytes32',
    'scriptnum': 'bigint', 'le64': 'bigint', 'le32': 'number',
};

function tsTypeForField(field) {
    if (field.arkType === 'bool') return 'boolean';
    return TS_TYPE_MAP[field.encoding] || 'Uint8Array';
}

function generateTypeScript(ir) {
    let out = '';
    out += `// Auto-generated by arkade-bindgen v0.1.0\n`;
    out += `// Source contract: ${ir.name}\n`;
    out += `// Compiler: arkade-compiler v${ir.compilerVersion}\n`;
    out += `// Do not edit manually.\n\n`;

    // Collect type aliases for imports
    const aliases = new Set();
    const sdkAliases = { 'compressed-33': 'Pubkey', 'schnorr-64': 'Signature', 'raw': 'Bytes', 'raw-20': 'Bytes20', 'raw-32': 'Bytes32' };
    const collectAliases = (fields) => fields.forEach(f => { if (sdkAliases[f.encoding]) aliases.add(sdkAliases[f.encoding]); });
    collectAliases(ir.constructorFields);
    ir.functions.forEach(fn => { collectAliases(fn.cooperative.userFields); collectAliases(fn.exit.userFields); });

    const imports = ['ArkContract', ...[...aliases].map(a => `type ${a}`)];
    out += `import { ${imports.join(', ')} } from "@arkade-os/contract-sdk";\n`;
    out += `import artifact from "./${toSnakeCase(ir.name)}.json";\n\n`;

    // Constructor params
    out += `/** Constructor parameters for ${ir.name} */\n`;
    out += `export interface ${ir.name}Params {\n`;
    for (const f of ir.constructorFields) {
        out += `  /** ${f.arkType} (${f.encoding}) */\n  ${toCamelCase(f.name)}: ${tsTypeForField(f)};\n`;
    }
    out += `}\n\n`;

    // Witness interfaces + class
    for (const func of ir.functions) {
        for (const [variant, label] of [[func.cooperative, 'Cooperative'], [func.exit, 'Exit']]) {
            const name = `${ir.name}${toPascalCase(func.name)}${label}Witness`;
            const pathLabel = label === 'Cooperative' ? 'cooperative path' : 'exit path';
            out += `/** Witness for ${ir.name}.${func.name} (${pathLabel}) */\n`;
            out += `export interface ${name} {\n`;
            for (const f of variant.userFields) {
                out += `  /** ${f.arkType} (${f.encoding}) */\n  ${toCamelCase(f.name)}: ${tsTypeForField(f)};\n`;
            }
            if (label === 'Cooperative') out += `  // serverSig injected by Ark server\n`;
            else if (variant.isNofnFallback) out += `  // N-of-N multisig exit fallback\n`;
            else out += `  // exit timelock enforced by script\n`;
            out += `}\n\n`;
        }
    }

    out += `export class ${ir.name} extends ArkContract<${ir.name}Params> {\n`;
    out += `  static readonly artifact = artifact;\n\n`;
    out += `  constructor(params: ${ir.name}Params) {\n`;
    out += `    super(${ir.name}.artifact, params);\n`;
    out += `  }\n`;

    for (const func of ir.functions) {
        const method = toCamelCase(func.name);
        const pascal = toPascalCase(func.name);
        out += `\n  ${method} = {\n`;
        out += `    cooperative: (witness: ${ir.name}${pascal}CooperativeWitness) =>\n`;
        out += `      this.buildWitness("${func.name}", true, witness),\n`;
        out += `    exit: (witness: ${ir.name}${pascal}ExitWitness) =>\n`;
        out += `      this.buildWitness("${func.name}", false, witness),\n`;
        out += `  };\n`;
    }
    out += `}\n`;
    return out;
}

// ─── Go backend ──────────────────────────────────────────────────────

const GO_TYPE_MAP = {
    'compressed-33': '[33]byte', 'schnorr-64': '[64]byte',
    'raw': '[]byte', 'raw-20': '[20]byte', 'raw-32': '[32]byte',
    'scriptnum': 'int64', 'le64': 'uint64', 'le32': 'uint32',
};

function goTypeForField(field) {
    if (field.arkType === 'bool') return 'bool';
    return GO_TYPE_MAP[field.encoding] || '[]byte';
}

function isFixedArray(encoding) {
    return ['compressed-33', 'schnorr-64', 'raw-20', 'raw-32'].includes(encoding);
}

const ENCODING_CONST = {
    'compressed-33': 'ark.Compressed33', 'schnorr-64': 'ark.Schnorr64',
    'raw': 'ark.Raw', 'raw-20': 'ark.Raw20', 'raw-32': 'ark.Raw32',
    'scriptnum': 'ark.ScriptNum', 'le64': 'ark.Le64', 'le32': 'ark.Le32',
};

function goValueExpr(field, prefix) {
    const goName = toPascalCase(field.name);
    if (field.encoding === 'scriptnum') {
        return field.arkType === 'bool'
            ? `ark.EncodeBool(${prefix}.${goName})`
            : `ark.EncodeScriptNum(${prefix}.${goName})`;
    }
    if (field.encoding === 'le64') return `ark.EncodeLe64(${prefix}.${goName})`;
    if (field.encoding === 'le32') return `ark.EncodeLe32(${prefix}.${goName})`;
    if (isFixedArray(field.encoding)) return `${prefix}.${goName}[:]`;
    return `${prefix}.${goName}`;
}

function generateGo(ir) {
    let out = '';
    const camelName = toCamelCase(ir.name);
    const receiver = ir.name[0].toLowerCase() === 'w' ? 'ct' : ir.name[0].toLowerCase();

    out += `// Code generated by arkade-bindgen v0.1.0. DO NOT EDIT.\n`;
    out += `// Source contract: ${ir.name}\n`;
    out += `// Compiler: arkade-compiler v${ir.compilerVersion}\n\n`;
    out += `package contracts\n\n`;
    out += `import (\n\t_ "embed"\n\t"github.com/arkade-os/contract-sdk-go/ark"\n)\n\n`;

    // Params struct
    out += `// ${ir.name}Params holds constructor parameters for the ${ir.name} contract.\n`;
    out += `type ${ir.name}Params struct {\n`;
    for (const f of ir.constructorFields) {
        out += `\t${toPascalCase(f.name)} ${goTypeForField(f)} // ${f.arkType} (${f.encoding})\n`;
    }
    out += `}\n\n`;

    // Witness structs
    for (const func of ir.functions) {
        for (const [variant, label] of [[func.cooperative, 'Cooperative'], [func.exit, 'Exit']]) {
            const structName = `${ir.name}${toPascalCase(func.name)}${label}Witness`;
            const pathLabel = label === 'Cooperative' ? 'cooperative path' : 'exit path';
            out += `// ${structName} holds witness data for ${ir.name}.${func.name} (${pathLabel}).\n`;
            out += `type ${structName} struct {\n`;
            for (const f of variant.userFields) {
                out += `\t${toPascalCase(f.name)} ${goTypeForField(f)} // ${f.arkType} (${f.encoding})\n`;
            }
            if (label === 'Cooperative') out += `\t// ServerSig injected by Ark server\n`;
            else if (variant.isNofnFallback) out += `\t// N-of-N multisig exit fallback\n`;
            else out += `\t// Exit timelock enforced by script\n`;
            out += `}\n\n`;
        }
    }

    // Contract struct
    out += `// ${ir.name} wraps an Ark contract instance.\n`;
    out += `type ${ir.name} struct {\n\t*ark.Contract\n}\n\n`;

    // Constructor
    out += `// New${ir.name} creates a new ${ir.name} contract instance.\n`;
    out += `func New${ir.name}(params ${ir.name}Params) (*${ir.name}, error) {\n`;
    out += `\tc, err := ark.NewContract(${camelName}Artifact, ark.ConstructorArgs{\n`;
    for (const f of ir.constructorFields) {
        out += `\t\t{Name: "${f.name}", Value: ${goValueExpr(f, 'params')}, Encoding: ${ENCODING_CONST[f.encoding] || 'ark.Raw'}},\n`;
    }
    out += `\t})\n`;
    out += `\tif err != nil {\n\t\treturn nil, err\n\t}\n`;
    out += `\treturn &${ir.name}{Contract: c}, nil\n}\n\n`;

    // Methods
    for (const func of ir.functions) {
        for (const [variant, label] of [[func.cooperative, 'Cooperative'], [func.exit, 'Exit']]) {
            const methodName = `${toPascalCase(func.name)}${label}`;
            const witnessType = `${ir.name}${toPascalCase(func.name)}${label}Witness`;
            const serverVariant = label === 'Cooperative';
            out += `// ${methodName} executes the ${label.toLowerCase()} path of ${func.name}.\n`;
            out += `func (${receiver} *${ir.name}) ${methodName}(w ${witnessType}) (*ark.WitnessStack, error) {\n`;
            out += `\treturn ${receiver}.BuildWitness("${func.name}", ${serverVariant}, []ark.WitnessField{\n`;
            for (const f of variant.userFields) {
                out += `\t\t{Name: "${f.name}", Value: ${goValueExpr(f, 'w')}, Encoding: ${ENCODING_CONST[f.encoding] || 'ark.Raw'}},\n`;
            }
            out += `\t})\n}\n\n`;
        }
    }

    out += `//go:embed ${toSnakeCase(ir.name)}.json\nvar ${camelName}Artifact []byte\n`;
    return out;
}

// ─── Public API ──────────────────────────────────────────────────────

export function generateBindings(jsonStr, target) {
    const artifact = JSON.parse(jsonStr);
    const ir = buildIR(artifact);
    switch (target) {
        case 'typescript': return generateTypeScript(ir);
        case 'go': return generateGo(ir);
        default: throw new Error(`Unknown target: ${target}`);
    }
}

export const AVAILABLE_TARGETS = [
    { value: 'typescript', label: 'TypeScript' },
    { value: 'go', label: 'Go' },
];
